language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
branches:
  only:
    - master
    - develop
before_script:
  - chmod -R a+x scripts
script:
  - ./scripts/dotnet-build.sh
  - ./scripts/dotnet-test.sh
  - ./scripts/dotnet-publish.sh
  - ./scripts/docker-build.sh
  - ./scripts/docker-publish.sh
after_success:
  - ./scripts/after-success.sh
notifications:
  email:
    on_success: never
    on_failure: always